language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jamesn8docker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesn8docker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-221279602931"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY